export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED'
export const PURCHASE_CAKE_START = 'PURCHASE_CAKE_START'
export const PURCHASE_CAKE_SUCCESS = 'PURCHASE_CAKE_SUCCESS'

export const PURCHASE_CAKE_FAIL = 'PURCHASE_CAKE_FAIL'